### ISSUE TITLE
Fix file read issue

### ISSUE THREAD

**Issue by bkiefer13** [UCSB-CS56-Projects/cs56-languages-vocab-quiz#1]
"ant jws" currently works and allows the user to play the game in a browser. But, when run from command line using "ant run", the vocabulary file is not being correctly read in. Fix this so that it can be run from command line. Also, make sure that it isn't hard coded in, so that other files with other languages could be read in instead.

~150 points

**Comment by pichumy** [comment]
ant run now works properly. there is also now a menu to choose which file to read in.

**Comment by ashedden** [comment]
This issue is still available! But issue #10 needs to be completed first.

**Comment by arda-** [comment]
fixed
