### ISSUE TITLE
"ant jws" Producing Browser Needing Permissions

### ISSUE THREAD

**Issue by ashedden** [UCSB-CS56-Projects/cs56-languages-vocab-quiz#10]
"ant jws" seems to produce a file that doesn't let users have permission to see. The web browser it produces doesn't even show up in the user's directory. Fixing this would be useful for issue #1  Estimated points ~200

**Comment by jmangel** [comment]
F16 (75 pts)

**Comment by jmangel** [comment]
Closed with #39
