### ISSUE TITLE
Keep track of variables

### ISSUE THREAD

**Issue by CrisCab** [UCSB-CS56-Projects/cs56-languages-vocab-quiz#28]
Correctly keep count and display significant variables. This includes the amount of incorrect guesses on a word (up to 3) and the amount of the total correct and incorrect answers. Incorrect answers increase when 3 incorrect guesses are made on one word. 
~100 pts

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by jmangel** [comment]
Closed with #33
