### ISSUE TITLE
Add more vocab for newly added languages

### ISSUE THREAD

**Issue by jrcryan** [UCSB-CS56-Projects/cs56-languages-vocab-quiz#4]
Currently, only a vocabulary list for German is included. Add vocab lists and the corresponding functionality to let user choose to be quizzed on other languages (Spanish, French, etc.)

~150 points

**Comment by pichumy** [comment]
Added functionality for this to be done. The actual vocab lists in question are not really populated yet, only a test file exists with one word each.

**Comment by ashedden** [comment]
This issues is still available! Functionality still needs to be implemented.

**Comment by jmangel** [comment]
Apparently has functionality, but some languages could use more words

**Comment by jmangel** [comment]
F16 OK (50 pts)

**Comment by jmangel** [comment]
Closed with #34
