### ISSUE TITLE
Add functionality to ask for "Hints" and "Skip"

### ISSUE THREAD

**Issue by pichumy** [UCSB-CS56-Projects/cs56-languages-vocab-quiz#7]
At the moment the quiz spits out a word at you, and you attempt to answer it. It would be nice to have functionality to ask for a "Hint" that may lead you towards the right answer, or an option to just "skip" the question if you don't know the answer.

**Comment by jrcryan** [comment]
approved
~200 points

**Comment by jmangel** [comment]
"Hint" functionality works; cannot test "skip" because the word never changes on my machine (BUG!)
