### ISSUE TITLE
Add difficulty levels

### ISSUE THREAD

**Issue by pichumy** [UCSB-CS56-Projects/cs56-languages-vocab-quiz#8]
At the moment the program just goes through the entire vocabulary list, and tests you on each one. It would be a nice functionality to have "difficulty" levels, and the program will select a different vocabulary list based on the difficulty level. This would require fixing the hard-coded FileRead code. This would also require making vocabulary lists divided in to difficulty levels.

**Comment by jrcryan** [comment]
approved
~300 points

**Comment by jmangel** [comment]
F16 OK (300 pts)

**Comment by jmangel** [comment]
closed with #38
